  FROM ubuntu:20.04
                                                                           
  RUN  apt update && apt install openssh-server sudo -y                       
  RUN  service ssh start                                                      
  EXPOSE 22 

  RUN  apt install nodejs -y
  RUN  apt install nano -y
  RUN  apt install curl -y
  RUN  apt install npm -y
  RUN  apt install git -y

  COPY ._/JSHs         /workspaces/._/JSHs 
  RUN  chmod 755   -R "/workspaces/._/JSHs/addUsers.sh" 
  RUN                 "/workspaces/._/JSHs/addUsers.sh"  nimda  bruce  robin 
  
  RUN  chmod 755      "/workspaces/._/JSHs/setNVS.sh" 
  RUN                 "/workspaces/._/JSHs/setNVS.sh"  18
                                 
  COPY ._2             /workspaces/._2 
  RUN  chmod 755   -R "/workspaces/._2/FRTs/setFRTs.sh" 
  RUN                 "/workspaces/._2/FRTs/setFRTs.sh" 

  RUN  rm -r           /workspaces/._ 

# RUN  mkdir       -p "/workspaces"
  RUN  chown nimda -R "/workspaces"                && chgrp nimda -R "/workspaces" 

# mkdir  -p            /workspaces/FRApps5
# RUN  chown nimda -R "/workspaces/FRApps5"        && chgrp nimda -R "/workspaces/FRApps5" 
  VOLUME               /workspaces/FRApps5
  COPY client1         /workspaces/FRApps5/client1 

  COPY client1         /workspaces/FRApps/client1 
  COPY server1         /workspaces/FRApps/server1 
  COPY server2         /workspaces/FRApps/server2 
  COPY server3         /workspaces/FRApps/server3 

  RUN  chown nimda -R "/workspaces/FRApps"         && chgrp nimda -R "/workspaces/FRApps" 
  RUN  chmod 775   -R "/workspaces/FRApps"  
          
  RUN  cd             "/workspaces/FRApps/client1" && npm install 
  RUN  cd             "/workspaces/FRApps/server1" && npm install 
  RUN  cd             "/workspaces/FRApps/server2" && npm install 
  RUN  cd             "/workspaces/FRApps/server3" && npm install 

# VOLUME               /workspaces/FRApps/client2  # Must be MT 
# VOLUME               /workspaces/FRApps           

  CMD ["/usr/sbin/sshd","-D"]           