  FROM ubuntu:20.04

  RUN apt update && apt install openssh-server sudo -y                       
  RUN service ssh start                                                      
  EXPOSE 22 

  RUN  useradd  -rm -s /bin/bash -d /home/nimda  -g root  -G sudo -u 1001 nimda   
  RUN  groupadd -g 1001 nimda 
  RUN  echo 'nimda:formR!2345'     | chpasswd 
  RUN  mkdir                        /home/nimda/.ssh && chmod 700 /home/nimda/.ssh && chown nimda /home/nimda/.ssh 
  COPY "._/.ssh/.profile"           /home/nimda 
  COPY "._/.ssh/authorized_keys"    /home/nimda/.ssh 

  RUN  useradd  -rm -s /bin/bash -d /home/bruce  -g nimda -G sudo -u 1002 bruce -d /home/bruce  
  RUN  echo 'bruce:formR!2345'     | chpasswd 
  RUN  mkdir                        /home/bruce/.ssh && chmod 700 /home/nimda/.ssh && chown nimda /home/nimda/.ssh
  COPY "._/.ssh/.profile"           /home/bruce 
  COPY "._/.ssh/authorized_keys"    /home/bruce/.ssh 

  RUN  useradd  -rm -s /bin/bash -d /home/robin  -g nimda -G sudo -u 1003 robin   
  RUN  echo 'robin:fmr.ram231'     | chpasswd  
  RUN  mkdir                        /home/robin/.ssh && chmod 700 /home/nimda/.ssh && chown nimda /home/nimda/.ssh
  COPY "._/.ssh/.profile"           /home/robin 
  COPY "._/.ssh/authorized_keys"    /home/robin/.ssh 

  RUN  mkdir         "/workspaces"
  RUN  chown nimda   "/workspaces" 
  RUN  chgrp nimda   "/workspaces" 

  CMD ["/usr/sbin/sshd","-D"]               